name: Latest Release Image Create and Push

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.IMAGE_UPLAOD_TOKEN }}
    - name: Build and Push Image to ghcr.io
      run: |
        docker build . -t ghcr.io/wizard-clock/wizarding-clock-server:latest
        docker push ghcr.io/wizard-clock/wizarding-clock-server:latest